version: '3.4'

services:
  backend:
    env_file:
      - env-backend.env
      - env-postgres.env
    build:
      context: ../backend
      dockerfile: dockerfiles/backend.dockerfile
    depends_on:
      - db
  db:
    build:
      context: ../backend
      dockerfile: dockerfiles/db.dockerfile
    env_file:
      - env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  traefik:
    image: traefik:v1.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
